### PR TITLE
Implement crazy-idea on JWT/Service

### PR DESCRIPTION
**Pull request by ijlyttle**
If/when merged, will fix #128, fix #76

Normally I'd make a draft PR, but I think I'll start this off as a "real" PR, as I think that would give you more opportunities to provide feedback.

I'll ask for a formal review when it's "ready", but please don't let that keep you from asking questions :)

### CODE REVIEW

**Comment by ijlyttle** [comment]
Just to make some notes as I go, the environment variable `BOX_USER_ID` keeps the `user` part because this is meant to refer to a user, rather than to use the more-generic term "account".

**Comment by ijlyttle** [comment]
At this point, with very limited testing, `box_auth_service()` seems to do what I want.

If I download the token into `~/.boxr-auth/token.json` and set the environment variable `BOX_USER_ID`:

```r
box_auth_service()
``` 

```
boxr: Authenticated using OAuth2 (JWT) as boxr-jwt-ijl (AutomationUser_868610_9SFx0Bq15D@boxdevedition.com)
● You may wish to add to your `.Renviron` file:
  BOX_TOKEN_FILE=~/.boxr-auth/token.json
  [Copied to clipboard]
● To edit your `.Renviron` file:
  - `usethis::edit_r_environ()`
  - check that `.Renviron` ends with a newline
```

```r
box_auth_service(account_id = box_user_id())
```

```
boxr: Authenticated using OAuth2 (JWT) as Ian Lyttle (ijlyttle@ians-email.com)
● You may wish to add to your `.Renviron` file:
  BOX_TOKEN_FILE=~/.boxr-auth/token.json
  [Copied to clipboard]
● To edit your `.Renviron` file:
  - `usethis::edit_r_environ()`
  - check that `.Renviron` ends with a newline
```

Next up, `box_dir_invite()`

**Comment by ijlyttle** [comment]
Quick note as I'm working on things: I can create a folder in the service account, invite my "real" user account, then view that folder from the web-portal using my account.

**Comment by nathancday** [comment]
This is AWESOME!!!

**Comment by ijlyttle** [comment]
I think I have things minimally-operational for `box_dir_invite()`.

Authorized as the service account, and having created a directory in the service-account file-space (nothing fancy, just used `box_dir_create()`):

```r
box_dir_invite("91114509755", role = "editor")
```

```
boxr-jwt-ijl (AutomationUser_868610_9SFx0Bq15D@boxdevedition.com) has invited Ian Lyttle (ijlyttle@ians-email.com) to collaborate on folder `bar` as editor.
```

Trying to create a collaboration twice results in a non-obvious API error-response - there's a whole other set of collaboration endpoints that can be useful, but I think this is all we need for now.

**Comment by ijlyttle** [comment]
I think this is at the point where it can be reviewed.

In the meantime, I'll start on the documentation here - if/when we merge this PR, I can continue documenting in the "main" PR.

Also, I might like to fiddle around with the whole Travis-CI thing while I'm here.

**Comment by nathancday** [comment]
I'll try to take a good look over this today.

Go ahead and fiddle with Travis. I think we need to re-encrypt (and add a new env var with the key) the token.file anyway

**Comment by ijlyttle** [comment]
Hi @nathancday,

I think  have made some progress:

- Travis testing works using the JWT token
- The app is server only - no user access
- `BOX_PASSWORD` is stored as a secret on Travis
- Tests are passing

We can replicate things so the tests run at the "official" site once you have all that sorted out.

**Comment by ijlyttle** [comment]
Had an idea for an internal function `box_auth_develop()` - this is now used in `teestthat/setup_auth.R` - if you have the `BOXR_PASSWORD`, this will auth you to the development account.

Might be handy for us, as we do dev stuff, so long as we aren't stepping on each other...

Just an idea...

**Pull request merged**
